# Node.js Build Only Pipeline for Juice Shop

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    echo "Installing dependencies..."
    npm ci
  displayName: 'Install dependencies'

- script: |
    echo "Building Juice Shop..."
    npm run build
  displayName: 'Build Juice Shop'
