# Node.js pipeline for OWASP Juice Shop
# Includes install, build, and test steps

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    echo "Installing dependencies..."
    npm ci
  displayName: 'Install dependencies'

- script: |
    echo "Building the application..."
    npm run build
  displayName: 'Build Juice Shop'

- script: |
    echo "Running tests..."
    npm test
  displayName: 'Run Tests'
